### PR TITLE
make use of queue optional

### PR DESCRIPTION
**Pull request by 2ank3th**
Made usage of queue optional so that multiple events from user does not lead to unintentional additions to the queue. This is uses queue by default. 

I have only changed one init for this. Should I add additional init methods ?

### CODE REVIEW

**Comment by devxoul** [comment]
@2ank3th, thank you for your work. But, why do we need this? Could you please provide example cases?

**Comment by 2ank3th** [comment]
I have a button which is supposed to increase the quantity of a selected item. Due to limits/availability plus button is disabled. Due to location of Toast(Or in general ignorance) user does not necessary notices the toast and clicks button multiple time. Each click is added to Queue. If he clicks 5 times the toast is visible for 10 seconds (ShortDelay).  

Another use case is when we use delay. 

With changes I committed toast is added to queue if no other toast is pending.

**Comment by devxoul** [comment]
@2ank3th I think you can check `JLToastCenter.defaultCenter().currentToast` instead:

```swift
func buttonDidSelect() {
    if JLToastCenter.defaultCenter().currentToast == nil {
        JLToast.makeText("The message").show()
    }
}
```

Alternatively, you can cancel all toasts queued and show a new one.

```
func buttonDidSelect() {
    JLToastCenter.defaultCenter().removeAllToasts()
    JLToast.makeText("The message").show()
}
```

**Comment by 2ank3th** [comment]
Yes, this works as well. I thought having it as part of library would be a good feature. Will use this instead. Thanks.

**Comment by devxoul** [comment]
Clarity is one of the most important thing in API design. Providing `useQueue` option is short, but using `currentToast` is more intuitive, I think. Thanks for understanding. :smile::+1:.

**Pull request closed without merging**
