### PR TITLE
fix memory leak

### PR DESCRIPTION
**Pull request by itlijunjie**
fix memory leak

### CODE REVIEW

**Comment by devxoul** [comment]
@itlijunjie, thanks for your work.
However, JLToastCenter and JLToastWindow is a singleton object. I think it's enough removing JLToastView from its superview when the animation ends.

**Comment by itlijunjie** [comment]
Sorry!About removing JLToastView,Probably is my read it wrong.
However,JLToastCenter and JLToastWindow no deinit?I feels inappropriate.

**Comment by devxoul** [comment]
Yes, JLToastCenter and JLToastWindow are not intended to be deinitialized. How about squash your commits? There's only a change, but there are 4 commits.

**Comment by devxoul** [comment]
Thanks!

**Pull request merged**
